on:
  push:
    branches:
      - master
 

jobs:
  
  build:
    runs-on: ubuntu-latest














    steps:
      
      uses: actions/checkout@v3

      - name: "docker login"
         run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TAKEN }}
        

        - name: "Building docker image"
         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ reham .

         - name: "pushing to Docker hub"
         run: docker push ${{ secrets.DOCKER_USERNAME }}/ reham
